id: DCDD614D8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:48:10+00:00'
last_modified: '2022-05-30T04:16:51.520807+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    ff47:
      image_group_id: I1PD95941
      title: སྦྱིན་པའི་གཏམ།
      total_pages: 1144
      order: 96
      base_file: ff47.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
